apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.55.0
      tlsAuth: false
      tlsAuthWithCACert: false

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
    jsonData:
      implementation: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: honeynet
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 1
      connMaxLifetime: 600