import { motion } from 'framer-motion';
import { AlertTriangle, Clock, MapPin, ShieldAlert, Zap } from 'lucide-react';
import { useMemo } from 'react';
import { timelineEvents as mockTimeline } from '../lib/mock-data';
import { Badge } from '../components/ui/badge';
import { Card } from '../components/ui/card';
import { useBackend } from '../lib/backend-context';

type Item = {
  id: string;
  title: string;
  description: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  timestamp: number;
  location: string;
  ip: string;
};

function severityTone(s: Item['severity']): string {
  switch (s) {
    case 'critical':
      return 'border-[#FF3D6E]/60 bg-[#FF3D6E]/15 text-[#FF3D6E]';
    case 'high':
      return 'border-orange-500/50 bg-orange-500/10 text-orange-300';
    case 'medium':
      return 'border-amber-400/50 bg-amber-400/10 text-amber-300';
    case 'low':
    default:
      return 'border-emerald-400/50 bg-emerald-400/10 text-emerald-300';
  }
}

function formatTime(ts: number) {
  return new Date(ts).toLocaleString('en-GB', {
    dateStyle: 'short',
    timeStyle: 'medium',
  });
}

type BackendAlert = {
  id: string;
  signature: string;
  description?: string;
  category?: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  src_ip: string;
  created_at: string;
};

type BackendEventRaw = {
  id: string;
  honeypot_id: string;
  event_type: string;
  protocol: string;
  src_ip: string | null;
  source_country?: string;
  payload?: Record<string, unknown>;
  created_at: string;
};

export function AttackTimeline() {
  const { alerts, events, usingMock } = useBackend();

  const items: Item[] = useMemo(() => {
    if (alerts && alerts.length > 0) {
      return (alerts as unknown as BackendAlert[]).slice(0, 20).map((a) => ({
        id: a.id,
        title: a.signature,
        description:
          a.description ?? a.category ?? 'Alert generated by the detection engine.',
        severity: a.severity,
        timestamp: new Date(a.created_at).getTime() || Date.now(),
        location: a.src_ip ?? '—',
        ip: a.src_ip ?? '—',
      }));
    }
    if (events && events.length > 0) {
      return (events as unknown as BackendEventRaw[]).slice(0, 20).map((e) => {
        const payload = e.payload ?? {};
        const description =
          (payload.command as string | undefined) ??
          (payload.uri as string | undefined) ??
          (payload.message as string | undefined) ??
          `${e.event_type} from ${e.src_ip ?? 'unknown'}`;
        return {
          id: e.id,
          title: `${e.protocol.toUpperCase()} probe`,
          description,
          severity: 'medium' as const,
          timestamp: new Date(e.created_at).getTime() || Date.now(),
          location: e.src_ip ?? '—',
          ip: e.src_ip ?? '—',
        };
      });
    }
    // Mock fallback uses the AttackEvent shape from mock-data.
    return mockTimeline.map((t, i) => ({
      id: t.id ?? `mock-${i}`,
      title: t.action ?? t.message ?? 'Detected event',
      description:
        `${t.message ?? ''} — ${t.protocol} from ${t.ip}`.trim(),
      severity: (t.threat ?? 'medium') as Item['severity'],
      timestamp: Date.now() - i * 7 * 60_000,
      location: t.countryName ?? t.country ?? 'Unknown',
      ip: t.ip ?? '—',
    }));
  }, [alerts, events]);

  return (
    <section id="timeline" className="container py-12 md:py-16">
      <div className="mb-6 flex items-end justify-between gap-4">
        <div>
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-[#00BFFF]/40 bg-[#00BFFF]/10 px-3 py-1 text-[10px] font-medium uppercase tracking-[0.18em] text-[#00BFFF]">
            <Clock className="h-3 w-3" /> Incident Timeline
          </div>
          <h2 className="font-display text-2xl font-semibold tracking-tight text-[#E6F1FF] md:text-3xl">
            Attack Forensics Timeline
          </h2>
          <p className="mt-1 text-sm text-[#8A9BB8]">
            {usingMock
              ? 'Demo timeline showing the typical kill-chain flow.'
              : 'Live alerts and notable events surfaced from the backend.'}
          </p>
        </div>
      </div>

      <Card className="p-6 md:p-8">
        <div className="relative ml-4">
          <div className="absolute left-[7px] top-2 bottom-2 w-px bg-gradient-to-b from-[#00BFFF] via-[#00BFFF]/40 to-transparent" />
          <ol className="space-y-6">
            {items.map((item, i) => (
              <motion.li
                key={item.id}
                initial={{ opacity: 0, x: -16 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true, amount: 0.3 }}
                transition={{ delay: i * 0.05, duration: 0.45 }}
                className="relative pl-8"
              >
                <span className="absolute left-0 top-1.5 grid h-4 w-4 place-items-center rounded-full border border-[#00BFFF]/60 bg-[#00BFFF]/20 shadow-[0_0_12px_rgba(0,191,255,0.6)]">
                  <span className="h-1.5 w-1.5 rounded-full bg-[#00BFFF]" />
                </span>

                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant="outline" className={`uppercase ${severityTone(item.severity)}`}>
                    <ShieldAlert className="mr-1 h-3 w-3" /> {item.severity}
                  </Badge>
                  <span className="text-xs text-[#8A9BB8]">{formatTime(item.timestamp)}</span>
                </div>
                <h3 className="mt-2 font-display text-lg font-semibold text-[#E6F1FF]">
                  {item.title}
                </h3>
                <p className="mt-1 text-sm leading-relaxed text-[#8A9BB8]">
                  {item.description}
                </p>
                <div className="mt-2 flex flex-wrap items-center gap-4 text-xs text-[#8A9BB8]">
                  <span className="inline-flex items-center gap-1.5">
                    <MapPin className="h-3.5 w-3.5 text-[#00BFFF]" /> {item.location}
                  </span>
                  <span className="inline-flex items-center gap-1.5 font-mono">
                    <AlertTriangle className="h-3.5 w-3.5 text-[#FF3D6E]" /> {item.ip}
                  </span>
                  <span className="inline-flex items-center gap-1.5">
                    <Zap className="h-3.5 w-3.5 text-[#00FF88]" /> correlated
                  </span>
                </div>
              </motion.li>
            ))}
          </ol>
          {items.length === 0 && (
            <div className="grid place-items-center py-16 text-sm text-[#8A9BB8]">
              No incidents captured yet — the mesh is quiet.
            </div>
          )}
        </div>
      </Card>
    </section>
  );
}