# Extra Redis exporter settings.
#
# Expose slowlog metrics:
#   SET redis_exporter_includeslowlog 1
# Expose all latency metrics:
#   SET redis_exporter_includelatency 1
# Custom check-modules directory for honeypet-specific counters
redis_exporter_includeslowlog: 1
redis_exporter_includelatency: 1